# Generated by Django 3.2 on 2022-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_blog', '0004_userpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
